// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StructuraFlow.Models;

#nullable disable

namespace StructuraFlow.Migrations
{
    [DbContext(typeof(StructuralDbContext))]
    partial class StructuralDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StructuraFlow.Models.ValidationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CheckBeamReferences")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckBeamStartEndSame")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckDuplicateBeams")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckDuplicateColumns")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckDuplicateSlabs")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckMissingFields")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckNegativeValues")
                        .HasColumnType("bit");

                    b.Property<double>("MinBeamLength")
                        .HasColumnType("float");

                    b.Property<double>("MinColumnHeight")
                        .HasColumnType("float");

                    b.Property<double>("MinColumnWidth")
                        .HasColumnType("float");

                    b.Property<double>("MinSlabThickness")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ValidationRules");
                });
#pragma warning restore 612, 618
        }
    }
}
